---
title: "Ementa"
author: "Ana Lu"
date: "16 de outubro de 2018"
output: html_document
---

# Minicurso Introdução ao R e aplicações na Macrometrópole



**Local:** Sala 004 do Prédio S do IEE/USP

**Professoras:** Dra. Ana Lucia Gerardi Spinola e Msc. Haydee Svab

**Monitora:** Msc. Beatriz Milz

## Parte 1: Introdução ao R e R Studio


9 – 10h  Instalação do R e R Studio, apresentação da linguagem e pacotes(Ana) [material]()

10 – 11h Carregando e salvando dados no R – working directory (Ana)

11 – 12h Exercícios Práticos [material]()

12 – 13h  Almoço

## Parte 2: Possíveis aplicações na Macrometrópole

13 – 14:30h Trabalhando com bancos de dados (Haydee)

14:30 – 15h Gráficos com ggplot2 (Bia) 

15 – 15:15h Intervalo

15:15 – 16h Análise de Redes Sociais, web scraping e mineração de texto (Ana) [material]()

16 – 17h Prática

Instalação de programas:

https://cran.r-project.org/

https://www.rstudio.com/products/rstudio/download/

O pacote "tidyverse" `install.packages("tidyverse")`

**Observação: os exercícios desse curso são baseados no material do Curso-R e na disciplina do Prof. Leonardo Barone.**

